// Mock data for the Tourist Guide Application

export const destinations = [
  {
    id: 'santorini',
    name: 'Santorini',
    country: 'Greece',
    description: 'A stunning Greek island known for its white-washed buildings, blue-domed churches, and breathtaking sunsets over the Aegean Sea.',
    image: 'https://images.unsplash.com/photo-1661602715735-d401dafd3615',
    rating: 4.8,
    coordinates: { lat: 36.3932, lng: 25.4615 },
    highlights: ['Sunset views in Oia', 'Volcanic beaches', 'Ancient Akrotiri ruins', 'Wine tasting tours'],
  },
  {
    id: 'kyoto',
    name: 'Kyoto',
    country: 'Japan',
    description: 'Ancient capital of Japan, home to thousands of temples, traditional gardens, and geisha culture.',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e',
    rating: 4.9,
    coordinates: { lat: 35.0116, lng: 135.7681 },
    highlights: ['Fushimi Inari shrine', 'Bamboo forest', 'Traditional tea ceremonies', 'Cherry blossoms'],
  },
  {
    id: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    description: 'Tropical paradise known for its forested volcanic mountains, iconic rice paddies, beaches and coral reefs.',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4',
    rating: 4.7,
    coordinates: { lat: -8.3405, lng: 115.0920 },
    highlights: ['Ubud rice terraces', 'Ancient temples', 'Surfing spots', 'Traditional dance'],
  },
  {
    id: 'marrakech',
    name: 'Marrakech',
    country: 'Morocco',
    description: 'A vibrant city filled with souks, palaces, and gardens. The red sandstone buildings give it a distinctive rose-colored appearance.',
    image: 'https://images.unsplash.com/photo-1597212618440-806262de4f6b',
    rating: 4.6,
    coordinates: { lat: 31.6295, lng: -7.9811 },
    highlights: ['Jemaa el-Fnaa square', 'Majorelle Garden', 'Spice markets', 'Moroccan cuisine'],
  },
  {
    id: 'reykjavik',
    name: 'Reykjavík',
    country: 'Iceland',
    description: 'Gateway to Iceland\'s stunning natural wonders including geysers, glaciers, and the Northern Lights.',
    image: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67',
    rating: 4.7,
    coordinates: { lat: 64.1466, lng: -21.9426 },
    highlights: ['Blue Lagoon', 'Northern Lights', 'Golden Circle', 'Hallgrímskirkja church'],
  },
  {
    id: 'barcelona',
    name: 'Barcelona',
    country: 'Spain',
    description: 'Cosmopolitan city known for Gaudí\'s architecture, beaches, and vibrant culture.',
    image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded',
    rating: 4.8,
    coordinates: { lat: 41.3851, lng: 2.1734 },
    highlights: ['Sagrada Familia', 'Park Güell', 'Gothic Quarter', 'Beach promenade'],
  },
];

export const placesByDestination = {
  santorini: {
    attractions: [
      {
        id: 'oia-village',
        name: 'Oia Village',
        category: 'attraction',
        description: 'Famous for its spectacular sunset views and iconic blue-domed churches. Wander through narrow streets filled with art galleries and cafes.',
        image: 'https://images.unsplash.com/photo-1661602715715-4db69e772aa3',
        rating: 4.9,
        coordinates: { lat: 36.4618, lng: 25.3753 },
        priceRange: 'Free',
        duration: '2-3 hours',
        bestTime: 'Sunset (7-9 PM)',
      },
      {
        id: 'akrotiri',
        name: 'Akrotiri Archaeological Site',
        category: 'attraction',
        description: 'Ancient Minoan city preserved by volcanic ash, often called the "Pompeii of the Aegean".',
        image: 'https://images.unsplash.com/photo-1601581987809-a874a81309c9',
        rating: 4.6,
        coordinates: { lat: 36.3569, lng: 25.4032 },
        priceRange: '€12',
        duration: '1-2 hours',
        bestTime: 'Morning',
      },
      {
        id: 'red-beach',
        name: 'Red Beach',
        category: 'attraction',
        description: 'Unique beach with dramatic red volcanic cliffs and crystal-clear waters.',
        image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19',
        rating: 4.4,
        coordinates: { lat: 36.3481, lng: 25.3929 },
        priceRange: 'Free',
        duration: '2-3 hours',
        bestTime: 'Morning or afternoon',
      },
    ],
    food: [
      {
        id: 'ambrosia',
        name: 'Ambrosia Restaurant',
        category: 'food',
        description: 'Fine dining with caldera views. Try the fresh seafood and local Santorini wines.',
        image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0',
        rating: 4.7,
        coordinates: { lat: 36.4186, lng: 25.4314 },
        priceRange: '€€€',
        cuisine: 'Mediterranean, Greek',
        specialties: ['Grilled octopus', 'Fava', 'Santorini tomato fritters'],
      },
      {
        id: 'lucky-souvlaki',
        name: 'Lucky\'s Souvlaki',
        category: 'food',
        description: 'Authentic Greek street food in the heart of Fira. Best gyros on the island!',
        image: 'https://images.unsplash.com/photo-1529058993007-b613d1ab4b7e',
        rating: 4.8,
        coordinates: { lat: 36.4168, lng: 25.4323 },
        priceRange: '€',
        cuisine: 'Greek Street Food',
        specialties: ['Pork gyros', 'Chicken souvlaki', 'Greek salad'],
      },
    ],
    hotels: [
      {
        id: 'grace-santorini',
        name: 'Grace Hotel Santorini',
        category: 'hotel',
        description: 'Luxury boutique hotel with infinity pool overlooking the caldera.',
        image: 'https://images.unsplash.com/photo-1728051104444-96d997be70ab',
        rating: 4.9,
        coordinates: { lat: 36.4285, lng: 25.4241 },
        priceRange: '€€€€',
        amenities: ['Infinity pool', 'Spa', 'Fine dining', 'Caldera views'],
      },
      {
        id: 'aroma-suites',
        name: 'Aroma Suites',
        category: 'hotel',
        description: 'Charming cave suites with traditional Cycladic architecture and modern comforts.',
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945',
        rating: 4.7,
        coordinates: { lat: 36.4175, lng: 25.4308 },
        priceRange: '€€€',
        amenities: ['Breakfast included', 'Jacuzzi', 'Sunset terrace', 'Cave rooms'],
      },
    ],
    culture: [
      {
        id: 'wine-museum',
        name: 'Santorini Wine Museum',
        category: 'culture',
        description: 'Explore the island\'s 3,500-year wine history in a unique underground cave setting.',
        image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3',
        rating: 4.5,
        coordinates: { lat: 36.3738, lng: 25.4517 },
        priceRange: '€15',
        duration: '1-2 hours',
        experience: 'Wine tasting included',
      },
      {
        id: 'traditional-village',
        name: 'Pyrgos Village',
        category: 'culture',
        description: 'Traditional village with medieval castle ruins and authentic local life.',
        image: 'https://images.unsplash.com/photo-1758745464235-ccb8c1253074',
        rating: 4.6,
        coordinates: { lat: 36.3890, lng: 25.4465 },
        priceRange: 'Free',
        duration: '2-3 hours',
        experience: 'Local artisan shops and traditional architecture',
      },
    ],
  },
  kyoto: {
    attractions: [
      {
        id: 'fushimi-inari',
        name: 'Fushimi Inari Shrine',
        category: 'attraction',
        description: 'Iconic shrine famous for thousands of vermillion torii gates winding up Mount Inari.',
        image: 'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36',
        rating: 4.9,
        coordinates: { lat: 34.9671, lng: 135.7727 },
        priceRange: 'Free',
        duration: '2-4 hours',
        bestTime: 'Early morning to avoid crowds',
      },
      {
        id: 'arashiyama-bamboo',
        name: 'Arashiyama Bamboo Grove',
        category: 'attraction',
        description: 'Enchanting bamboo forest with towering stalks creating a magical atmosphere.',
        image: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186',
        rating: 4.8,
        coordinates: { lat: 35.0094, lng: 135.6678 },
        priceRange: 'Free',
        duration: '1-2 hours',
        bestTime: 'Early morning',
      },
    ],
    food: [
      {
        id: 'kikunoi',
        name: 'Kikunoi',
        category: 'food',
        description: 'Three-Michelin-star kaiseki restaurant offering seasonal Japanese haute cuisine.',
        image: 'https://images.unsplash.com/photo-1741855900000-7c1cacddfeac',
        rating: 4.9,
        coordinates: { lat: 35.0031, lng: 135.7809 },
        priceRange: '€€€€',
        cuisine: 'Kaiseki',
        specialties: ['Seasonal tasting menu', 'Traditional tea ceremony'],
      },
      {
        id: 'nishiki-market',
        name: 'Nishiki Market',
        category: 'food',
        description: 'Five-block-long covered market selling fresh seafood, produce, and Kyoto specialties.',
        image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5',
        rating: 4.7,
        coordinates: { lat: 35.0050, lng: 135.7656 },
        priceRange: '€-€€',
        cuisine: 'Various Japanese',
        specialties: ['Takoyaki', 'Fresh sushi', 'Pickled vegetables'],
      },
    ],
    hotels: [
      {
        id: 'hoshinoya-kyoto',
        name: 'Hoshinoya Kyoto',
        category: 'hotel',
        description: 'Exclusive riverside ryokan accessible only by boat, blending tradition and luxury.',
        image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa',
        rating: 4.9,
        coordinates: { lat: 35.0089, lng: 135.6762 },
        priceRange: '€€€€',
        amenities: ['Private boat access', 'Onsen', 'Kaiseki dining', 'River views'],
      },
    ],
    culture: [
      {
        id: 'tea-ceremony',
        name: 'Traditional Tea Ceremony',
        category: 'culture',
        description: 'Experience authentic Japanese tea ceremony in a historic machiya townhouse.',
        image: 'https://images.unsplash.com/photo-1580933073521-dc49ac0d4e6a',
        rating: 4.8,
        coordinates: { lat: 35.0116, lng: 135.7681 },
        priceRange: '€40',
        duration: '1.5 hours',
        experience: 'Learn tea ceremony etiquette and enjoy matcha with wagashi',
      },
    ],
  },
  // Add more destinations with similar structure...
};

export const chatResponses = {
  greetings: [
    "Hello! I'm your local guide. Ask me anything about your destination!",
    "Welcome, traveler! Ready to explore? What would you like to know?",
    "Hey there! I'm here to help you discover the best of this place.",
  ],
  'one-day': {
    santorini: "Perfect! Here's my one-day Santorini itinerary:\n\n🌅 Morning (8-11am): Start in Oia village - explore the narrow streets before crowds arrive. Grab breakfast at a local bakery.\n\n☀️ Midday (11am-2pm): Visit Akrotiri Archaeological Site, then head to Red Beach for a swim.\n\n🍽️ Lunch (2-3pm): Try Lucky's Souvlaki in Fira for authentic Greek street food.\n\n🌆 Afternoon (3-6pm): Wine tasting tour at a local winery - Santorini's volcanic wines are unique!\n\n🌅 Sunset (7-9pm): Return to Oia for the famous sunset. Arrive early to get a good spot!\n\nPro tip: Rent an ATV to get around - it's the most fun and flexible way to explore the island!",
    kyoto: "Here's how to make the most of one day in Kyoto:\n\n🌸 Early Morning (6-8am): Fushimi Inari Shrine - beat the crowds and catch the mystical morning atmosphere among the torii gates.\n\n🎋 Morning (9-11am): Arashiyama Bamboo Grove and nearby Tenryu-ji Temple gardens.\n\n🍜 Lunch (12-1pm): Nishiki Market - try various street foods and local specialties.\n\n⛩️ Afternoon (2-5pm): Kinkaku-ji (Golden Pavilion) and Ryoan-ji zen garden.\n\n🍵 Late Afternoon (5-6pm): Traditional tea ceremony experience.\n\n🌃 Evening (7-9pm): Gion district - spot geishas and enjoy dinner in a traditional restaurant.\n\nPro tip: Get a one-day bus pass (¥700) - it covers most major attractions!",
  },
  'best-food': {
    santorini: "You're in for a treat! Here are my top food recommendations:\n\n🐙 Must-try dishes:\n• Fava - creamy yellow split pea puree (vegetarian & delicious!)\n• Tomatokeftedes - Santorini tomato fritters\n• Fresh grilled octopus with local wine\n• Greek yogurt with Santorini honey\n\n🍷 Wine: Don't miss Assyrtiko wine - unique to Santorini's volcanic soil.\n\n🍴 Where to eat:\n• Lucky's Souvlaki (budget-friendly, authentic)\n• Ambrosia Restaurant (splurge-worthy sunset views)\n• Any family taverna in Pyrgos village (local experience)\n\n🥙 Street food tip: Try a gyros from any local souvlaki place - they're all amazing!\n\nAvoid restaurants with aggressive touts in Fira - they're usually tourist traps.",
    kyoto: "Kyoto is a food lover's paradise! Here's what you can't miss:\n\n🍱 Must-try experiences:\n• Kaiseki - multi-course seasonal Japanese meal\n• Matcha everything - Kyoto is the birthplace of Japanese tea culture\n• Yudofu - delicate tofu hot pot (specialty of Kyoto)\n• Obanzai - traditional Kyoto home-style dishes\n\n🍜 Best spots:\n• Nishiki Market - one-stop for street food sampling\n• Gion district - traditional restaurants and teahouses\n• Kikunoi - if you want a splurge-worthy kaiseki experience\n\n🍡 Street food picks:\n• Matcha soft serve\n• Takoyaki (octopus balls)\n• Yatsuhashi (cinnamon rice crackers)\n• Fresh mochi\n\n💡 Pro tip: Many restaurants don't take reservations and have limited English menus - embrace the adventure!",
  },
  'hidden-gems': {
    santorini: "Ah, you want the local secrets! Here are places tourists often miss:\n\n🏖️ Vlychada Beach - dramatic lunar-like landscape, far fewer crowds than famous beaches.\n\n🏘️ Megalochori village - authentic Santorini life, local tavernas, no cruise ship crowds.\n\n🍷 Small family wineries in Megalochori - skip the big tourist ones, ask locals for recommendations.\n\n📚 Atlantis Books in Oia - charming independent bookshop, perfect hideaway spot.\n\n🌅 Skaros Rock - alternative sunset spot with amazing views, requires a short hike.\n\n🍴 Tavernas in Emporio - the most authentic food at half the price of Oia.\n\nLocal tip: Visit in shoulder season (May or October) - still warm, but way fewer crowds!",
  },
  'budget-tips': "Great question! Travel doesn't have to break the bank:\n\n💰 Save money by:\n• Eating where locals eat (away from main squares)\n• Taking public transport or walking\n• Visiting free attractions early morning\n• Staying in family-run guesthouses\n• Shopping at local markets for snacks\n\n🎫 Many museums have free admission days - ask at tourist information.\n\n🥪 Lunch is usually cheaper than dinner at the same restaurant!\n\n💡 Pro tip: Book accommodations with breakfast included - saves time and money.",
  'family-friendly': "Traveling with family? Here are my kid-friendly recommendations:\n\n👨‍👩‍👧‍👦 Family activities:\n• Beach time (obviously!)\n• Easy walking tours with interesting stories\n• Interactive museums\n• Cooking classes\n• Boat trips\n\n🍽️ Family-friendly restaurants usually have high chairs and simple menus.\n\n⏰ Best times: Morning activities (before kids get tired) and early dinner (5-6pm works best).\n\n💡 Tip: Many attractions offer family discounts - always ask!",
  'safety': "Safety first! Here's what you need to know:\n\n✅ Generally very safe for tourists:\n• Keep regular precautions (watch valuables in crowds)\n• Stay in well-lit areas at night\n• Use official taxis or ride-share apps\n\n🚨 Emergency numbers:\n• Police: 100 (varies by country)\n• Tourist police: Usually have English speakers\n\n💊 Have travel insurance and know where nearest hospital is.\n\n📱 Keep important contacts saved offline.\n\n💡 Tip: Make copies of your passport and keep them separate from the original.",
  default: "I'd love to help you with that! As your local guide, I can tell you about:\n\n🗺️ Best things to do in one day\n🍽️ Where to find the best local food\n💎 Hidden gems tourists miss\n💰 Budget-friendly tips\n👨‍👩‍👧‍👦 Family-friendly activities\n🏨 Hotel recommendations\n🚗 Getting around\n⚠️ Safety tips\n\nWhat would you like to know?",
};

export default {
  destinations,
  placesByDestination,
  chatResponses,
};
